import { createRoot } from 'react-dom/client'
import '@fontsource/orbitron/400.css'
import '@fontsource/orbitron/700.css'
import '@fontsource/rajdhani/500.css'
import '@fontsource/rajdhani/700.css'
import '@fontsource/exo-2/400.css'
import '@fontsource/exo-2/600.css'
import '@fontsource/share-tech-mono/400.css'
// Frontier
import '@fontsource/saira-stencil-one/400.css'
import '@fontsource/rye/400.css'
import '@fontsource/barlow/400.css'
import '@fontsource/barlow/600.css'
// Elven Realm
import '@fontsource/cinzel/400.css'
import '@fontsource/cinzel/600.css'
import '@fontsource/cinzel-decorative/400.css'
import '@fontsource/eb-garamond/400.css'
import '@fontsource/eb-garamond/600.css'
// Shadow Realm
import '@fontsource/pirata-one/400.css'
import '@fontsource/unifrakturcook/700.css'
import '@fontsource/alegreya/400.css'
import '@fontsource/alegreya/700.css'
// Digital Rain / Zero Day / Neon City / Retro Desktop
import '@fontsource/vt323/400.css'
import '@fontsource/ibm-plex-mono/400.css'
import '@fontsource/ibm-plex-mono/600.css'
import '@fontsource/audiowide/400.css'
import '@fontsource/monoton/400.css'
import '@fontsource/pixelify-sans/400.css'
import '@fontsource/pixelify-sans/600.css'
import '@fontsource/silkscreen/400.css'
// Steampunk / Noir / High Seas
import '@fontsource/im-fell-english-sc/400.css'
import '@fontsource/im-fell-english/400.css'
import '@fontsource/libre-baskerville/400.css'
import '@fontsource/libre-baskerville/700.css'
import '@fontsource/special-elite/400.css'
import '@fontsource/courier-prime/400.css'
import '@fontsource/courier-prime/700.css'
import '@fontsource/limelight/400.css'
import '@fontsource/jolly-lodger/400.css'
// Zen Garden / Eldritch
import '@fontsource/shippori-mincho/400.css'
import '@fontsource/shippori-mincho/600.css'
import '@fontsource/quicksand/400.css'
import '@fontsource/quicksand/600.css'
import '@fontsource/im-fell-dw-pica-sc/400.css'
import '@fontsource/crimson-text/400.css'
import '@fontsource/crimson-text/600.css'
import '@fontsource/grenze-gotisch/500.css'
import './styles.css'
import './universes.css'
import './universes-digital.css'
import './universes-worlds.css'
import { App } from './App'

createRoot(document.getElementById('root')!).render(<App />)
